matrix:
  include:
  - os: osx
    sudo: required
    language: generic
    env:
    - HOMEBREW_NO_AUTO_UPDATE=1
    before_install:
    - brew install webp jsoncpp
    - sudo pip install pytest
  - os: linux
    dist: trusty
    sudo: required
    language: python
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libpng-dev libjsoncpp-dev
    - curl "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.6.0-linux-x86-64.tar.gz" -o libwebp-0.6.0-linux-x86-64.tar.gz
    - tar -xvzf libwebp-0.6.0-linux-x86-64.tar.gz
    - sudo mv libwebp-0.6.0-linux-x86-64/bin/cwebp /usr/local/bin/
    - sudo mv libwebp-0.6.0-linux-x86-64/bin/webpmux /usr/local/bin/
install:
- cd apng2webp_dependencies
- mkdir build
- cd build
- cmake -DSTATIC_LINKING=TRUE ..
- make
- sudo make install
- cd $TRAVIS_BUILD_DIR
- sudo python setup.py install
script:
- cd $TRAVIS_BUILD_DIR
- sudo python setup.py test
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - mkdir deploy
  - cp /usr/local/bin/apng2webp_apngopt .
  - cp /usr/local/bin/apngdisraw .
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -czvf deploy/apng2webp_dependencies-osx.tar.gz apng2webp_apngopt apngdisraw ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -czvf deploy/apng2webp_dependencies-linux.tar.gz apng2webp_apngopt apngdisraw ; fi
deploy:
  provider: releases
  api_key:
    secure: qaaJnR83BIHniYf1o7AmnkiHxyxadq5MNMqI0FEyezgjaFme0AD0LSqo0XYnHZLeY6G9GdTqVZl1Vs8MYd/GxqHrL/re0aNmL4x9cawi26EWw/cIbr7Wrgv7c94+4QobdJOfa/fJHqBPsWmOxX5oslwl5MSuzPql5nMInZMOYgyDH5Hq8BSS9A5ed44C0qR5RwwvsgBOPR3ul4N66XxNFuTlqbiMNRWQ4vgl3T4Gus97waLu8TxcV/hKcTGUyS6W24CbgX8QKX5ymyWVZPnwyeZfgiSs+KTSoUQSqH4ezkzzq9rEYuuhlOeEkgSgvz+hOJqStI7SdoGKYCOJSwjbEjLAxrrJy+9BzQNiIkKUH7yKVLF47tw2mlekr6PejjAy4vShoV6ocbFnQFvsdxELdEeafVeNh9LRvjno5AoLM0wR+iEJPg0JF6WgyhqOPhqf8zG4YHYZqgV4VIGmTybchN1RZ6lIvBLb5h8BNx4XeLj89PnWfPkYtKkSQ4wVJw6LJLHHxABjTG2WYOyHYyrxYWZqXT+JnJVlaqFrYJ/9yMuKyxTie1DtQXFn430/sQ8Ps69SVo6g/gUkETlhoJNvtu8NJ6myJIQ4beLjwX2QooRzDPVlYX5PpoCaA+tMGelBgyeOO5bi0B3OBtaAjBmrqF30VyApBxUKhvgzwaZdumo=
  file_glob: true
  file: $TRAVIS_BUILD_DIR/deploy/*
  skip_cleanup: true
  on:
    tags: true
    repo: Benny-/apng2webp
